
# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    main: main.go
    binary: iterm-cmd

archives:
  - replacements:
      amd64: x86_64
    files:
    - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

# From: https://medium.com/@ben.lafferty/deploying-go-cli-applications-316e9cca16a4
brews:
  - github:
        owner: oliverisaac
        name: homebrew-tap
    folder: Formula
    homepage: https://github.com/oliverisaac/iterm-cmd
    description: Generate files that contain commands and be cmd-clicked inside iTerm2

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'README'
      - Merge pull request
      - Merge branch
