#!/usr/bin/env bash

set -euo pipefail

EDITOR="${EDITOR:-vim}"
ITERM2_CMD_DIR="${ITERM2_CMD_DIR:-/tmp/it2cmd}"

function handle_click(){
    file="$1"
    line_number="${2:-}"

    itermRegex="^${ITERM2_CMD_DIR%/}/([a-f0-9A-F]+)$"
    if [[ ${ITERM2_CMD_ENABLED:-false} == true ]] && [[ "$file" =~ $itermRegex ]]; then
        cat "$file"
        echo
    elif [[ -f "$file" ]]; then
        args=( "${EDITOR}" )

        # Set the line number
        if [[ -n "$line_nubmer" ]]; then
            if [[ ${EDITOR} == vim ]] || [[ $EDITOR == vi ]]; then
                args=( +${line_number} )
            elif [[ ${EDITOR} == code ]]; then # visual studio code
                args=( -g "$file:${line_number}" )
            fi
        fi
        printf "%q " "${args[@]}"
        echo
    else
        printf 'echo "< $PWD ^ $( dirname %q )"; cd %q; ls;\n' "$file" "$file"
    fi
}

handle_click "${@}"
